package com.projects.teamsync.enums;

public enum NotificationType {

    APPLICATION_RECEIVED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,

    INVITATION_RECEIVED,
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,

    MEMBER_REMOVED,
    MEMBER_LEFT,

    REFERRAL_RECEIVED,
    REFERRAL_ACCEPTED,
    REFERRAL_REJECTED
}